#!/usr/bin/python3
# SPDX-FileCopyrightText: 2024 Yamato Nunomura
import sys
   
def tonum(s):
    try:
        return int(s)
    except:
        return float(s)

ans = 0
for line n sys.stdin:
        ans += tonum(line)

print(ans)
